version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8000:80"
    environment:
      - ENVIRONMENT=dev
      - LOG_LEVEL=debug
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
